apiVersion: v1
kind: Service
metadata:
  name: wikiserver
spec:
  selector:
    app: wikiserver
  type: LoadBalancer
  ports:
  - name: wiki-port
    port: 80
    targetPort: 80
  loadBalancerIP: 192.168.1.212
