apiVersion: v1
kind: Service
metadata:
  name: wikiserver
  namespace: wikiserver
spec:
  selector:
    app: wikiserver
  type: LoadBalancer
  ports:
  - name: wiki-port
    port: 80
    targetPort: 80
  loadBalancerIP: 192.168.1.218
  externalIPs: 
    [192.168.1.218]  
