{
 "title": "New dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "GO GC Heap Frees by Size bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "go_gc_heap_frees_by_size_bytes_count",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  { "title": "Longhorn", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Loghorn Unfinished Work seconds",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "longhorn_workqueue_unfinished_work_seconds",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Longhorn Disk Status",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 10 },
   "targets": [
    { "expr": "longhorn_disk_status", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Loghorn Disk Usage bytes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 10 },
   "targets": [
    { "expr": "longhorn_disk_usage_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Longhorn Node Count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 15, "y": 10 },
   "targets": [
    { "expr": "longhorn_node_count_total", "legendFormat": "__auto" }
   ]
  },
  { "title": "Containers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Cntnr FS Usage bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 17 },
   "targets": [
    { "expr": "container_fs_usage_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Cntnr Threads",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 17 },
   "targets": [
    { "expr": "container_threads", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Cntnr blkio usage total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 17 },
   "targets": [
    {
     "expr": "container_blkio_device_usage_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cntnr CPU seconds Total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 15, "y": 17 },
   "targets": [
    {
     "expr": "container_cpu_system_seconds_total",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}