#!/bin/bash
# get CPU stats
line=`iostat -c | grep  "^\s"`
arr=(`echo ${line}`)
echo {\"hostname\": \"`hostname`\",
echo \"cpu\":{
echo \"user\": ${arr[0]},
echo \"nice\": ${arr[1]},
echo \"system\": ${arr[2]},
echo \"iowait\": ${arr[3]},
echo \"steal\": ${arr[4]},
echo \"idle\": ${arr[5]}
echo "},"
# get temperature
templine=`sensors | grep temp1`
words=($templine)
echo \"temperature\": \"${words[1]}\",
# get disk space
echo  \"disks\": [

iostat -m | tail -n +7 | while read LN; do
  if [ ! -z "$LN" ]; then 
    columns=(`echo $LN`)
    # add comma if further volumes
    if [[ -v HASDISK ]];
    then
      echo ,
    fi
    echo {\"dev\":\"${columns[0]}\",
    echo \"tps\":${columns[1]},
    echo \"MBReadPs\":${columns[2]},
    echo \"MRWritePs\":${columns[3]},
    echo \"MBRead\":${columns[4]},
    echo \"MBWritten\":${columns[5]}}
    HASDISK=true
  fi
done
echo "]"
echo "}"
