apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: git-pvc
  namespace: git-server
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-nvme
  resources:
    requests:
      storage: 5Gi
