apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: mysql-server
spec:
  selector:
    app: mysql
  type: LoadBalancer
  loadBalancerIP: 192.168.1.210
  ports:
  - name: mysql-port
    port: 3306
    targetPort: 3306

