apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: monitoring
spec:
  ports:
  - name: web
    port: 9091
    targetPort: web
  selector:
    prometheus: prometheus-persistant
  sessionAffinity: ClientIP
